// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pynxuncunsicifxvloms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bnh1bmN1bnNpY2lmeHZsb21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1ODQ2MTEsImV4cCI6MjA3NzE2MDYxMX0.dC8M_gITEXf49z9z_MZYQxfQHCniKjnuGJ9mRO6vV3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);