// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://byogjmmqittubypowoyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5b2dqbW1xaXR0dWJ5cG93b3liIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ5MDkxODgsImV4cCI6MjA4MDQ4NTE4OH0.OHrK8sA1vJ-PzivfxEhZY5aqnsMxJuOwj7yYKzETlWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);