// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://cxntiszohzgntyhbagga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bnRpc3pvaHpnbnR5aGJhZ2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzNjQ1MzcsImV4cCI6MjA3Nzk0MDUzN30.ERxQ64BCprxGoeLTvf_-ulEYx0JVDAEy9BnwGBnEbCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);